### PR TITLE
352 change password

### PR DESCRIPTION
**Pull request by lapinlapin**
#### What's this PR do?
Added forms of change password
#### Where should the reviewer start?
views/ChangePassword/
#### How should this be manually tested?
https://localhost:8080/
#### What are the relevant tickets?
#352 
#### Screenshots (if appropriate)
image
image

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/branch-352-change-password

### CODE REVIEW

**Comment by noeminik** [comment]
@lapinlapin 
- Change password should be available only for 'secure key' account
- in change password popup please make the 'cancel' button look similar to 'confirm order's screen 'cancel' (now the next and cancel look same)
- while changing the password, it is visible (currently the labels are too close to the input, but assuming with *** should look fine).
image

**Comment by lapinlapin** [comment]
@noeminik 
**Change password should be available only for 'secure key' account** @youaresofunny Anton said he would do it.

-Cancel button - fixed
-Hide passwords - fixed

**Comment by noeminik** [comment]
@lapinlapin ui fixed
@youaresofunny the change password functionality itself doesn't work. so after changing the pass still logged in with the old password (new is invalid), don't know if that relates to merging.

**Comment by youaresofunny** [comment]
@noeminik Check it please

**Review by youaresofunny — APPROVED** [review]

**Pull request merged**
